import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.css";
import { Header } from "../../ui_components/Header";
import { Footer } from "../../ui_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-bg`}>
        <div className="">
          <Header />
          <main className=" h-full ">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
